graphai:
  user: USERNAME
  password: PASSWORD
  url: "https://graphai.epfl.ch/"

mysql:
  client_bin: /usr/local/mysql/bin/mysql
  dump_bin: /usr/local/bin/mysqldump
  server_test: graph_engine_test
  server_prod: graph_prod
  graph_engine_test:
    username: USERNAME
    password: PASSWORD
    host_address: HOST_ADDRESS
    port: PORT
  graph_prod:
    username: USERNAME
    password: PASSWORD
    host_address: HOST_ADDRESS
    port: PORT
  data_path:
    formula: database/formulas/mysql
    export: data/mysql_data_dumps
  db_schema_names:
    ontology: graph_ontology_light # Which one to use in knowledge graph construction
    ontology_light: graph_ontology_light
    ontology_full: graph_ontology
    registry: graph_registry
    lectures: graph_lectures
    airflow: graph_airflow
    elasticsearch_cache: elasticsearch_cache
    graph_cache_test: graph_cache
    graph_cache_prod: graph_cache
    graphsearch_test: graphsearch_test
    graphsearch_prod: graphsearch_prod
    website: website

elasticsearch:
  test_env:
    hostname: HOSTNAME
    port: 0000
    username: USERNAME
    password: PASSWORD
  prod_env:
    hostname: HOSTNAME
    port: 0000
    username: USERNAME
    password: PASSWORD
  data_export_path: /path/to/data/export
  index_date: 2025-09-20
  index_file: 2025-09-20/es_fullindex_2025-09-20.json.gz
  index_names:
    graphsearch_test: graphsearch_test_2025_09_20
    graphsearch_prod: prod_index_name
